### ISSUE TITLE
ordfeminine in italic

### ISSUE THREAD

**Issue by laerm0** [laerm0/opensans#1]
![screen region 2018-05-30 at 11 12 03](https://user-images.githubusercontent.com/10780161/40735276-beae6180-6408-11e8-902c-a08a71bee4df.png)

It's single-story in the regular but two-story in the condensed. 🤔 I'm inclined to go single-story on all, @davelab6. Thoughts?

**Comment by davelab6** [comment]
Yep agree

**Comment by davelab6** [comment]
@laerm0 I suggest closing this and PR'ing all the changes here to the GF org, and then I will give you direct commit access to that repo :)

**Comment by davelab6** [comment]
You already have direct access :)
