### ISSUE TITLE
Normalize UFO and document how to do so

### ISSUE THREAD

**Issue by moyogo** [laerm0/opensans#11]
Normalizing UFOs can make commits smaller and diffs more relevant.
As mentioned in #10, you can either use a tool like [ufoNormalizer](https://github.com/unified-font-object/ufoNormalizer) or fontTools.ufoLib, or also [psfnormalize](https://github.com/silnrsi/pysilfont).

Whichever one you pick, please document it so any contributor can use the same.

**Comment by laerm0** [comment]
Hi @moyogo –

Based on @anthrotype's input at https://github.com/laerm0/opensans/pull/10#issuecomment-491310557, I don't think I need to normalize. The build path here will use fontTools.ufoLib for the foreseeable future, so I'll stick with what I know unless there's a pressing reason to change (i.e. if this switches from Glyphs to UFO source).

**Comment by moyogo** [comment]
Please indicate this in the README.md. I’m just thinking of the case where someone submits a merge request made with another UFO writer where the normalization is different.

**Comment by laerm0** [comment]
Excellent point. I will do so.

**Comment by laerm0** [comment]
Closing as README is now updated.
