### ISSUE TITLE
hinting regressions

### ISSUE THREAD

**Issue by laerm0** [laerm0/opensans#14]
There will be hinting regressions on the accented glyphs because these files were originally hinted by someone at Ascender <coughs> many years ago and they used special functions to position accents. Those functions became the IP of Monotype once Monotype bought Ascender. Because this is proprietary information (albeit proprietary information that I have partially forgotten), those techniques cannot be used again. As I am clearly not a lawyer, I don't want to drag any of that info out of my head to use again.

Anyway, the result you will see is that there will be occasional accent collision and bouncing at small sizes.

<img width="164" alt="screenshot_2019-06-22_13-19-46" src="https://user-images.githubusercontent.com/10780161/59966893-7e16dc00-94f0-11e9-8205-7fc8ad64733c.png">
_example_

Perhaps with the aid of @josh-hadley I can rewrite these functions and make them look "different" enough to pass muster with lawyers, but because it's essentially assembly code, the stuff will kinda always be in the same order.

This is all way outta my pay grade, so opinions welcome from @davelab6 and @rsheeter.

**Comment by davelab6** [comment]
I suggest closing this as we'll deal with the hinting differently to what was done for the legacy static fonts :)

**Comment by laerm0** [comment]
ttfautohint them or keep the manual hints?
