### ISSUE TITLE
Instances will never match source TTFs

### ISSUE THREAD

**Issue by laerm0** [laerm0/opensans#21]
This isn't a solvable issue; it's a note for future users.

These files were originally designed without the aid of multiple masters; therefore, there will be slight differences between stem weights throughout and some consistency/predictability lacking in the vertical design dimension (vertical = in a specific glyph between weights; horizontal = in a specific weight among glyphs). 

These GIFs show this. The glyphs with the red bars are from the original TTFs. 

Regular
![H-semibold](https://user-images.githubusercontent.com/10780161/63616581-df712f00-c5b5-11e9-9b6e-42572f66f867.gif)

Semibold
![H-bold](https://user-images.githubusercontent.com/10780161/63616593-e6983d00-c5b5-11e9-9214-b7eb76c26e38.gif)

The interpolations between weights used the [Pablo distribution](https://glyphsapp.com/tutorials/multiple-masters-part-3-setting-up-instances). The weights match ±2 units in the _horizontal_ dimension: getting them to match in the vertical dimension – i.e. horizontal stems – would require a different weight value than the horizontal dimension. As vertical stems are more common and more important to legibility than horizontal stems, the decision was made to make sure those are correct. Interpolation by different values in the X and Y directions is currently unsupported, so this isn't happening.

Another solution would be to find which glyphs are off the most and then set up sparse masters for them. A sparse master is a master that would otherwise be an interpolation and has an incomplete glyph set. This is supported, however, it would also greatly increase the file size, offsetting the gains by going to variable fonts.

For added fun, this awkward relationship between weights also means the sidebearings are not equal to source glyphs. Hopefully the improved kerning takes care of this (and provides an upgrade across the board).

**Comment by davelab6** [comment]
I'm fine with these minor differences, I suggest closing this
