### ISSUE TITLE
switching to UFO + designspace source

### ISSUE THREAD

**Issue by laerm0** [laerm0/opensans#5]
The build process for a font with multiple axes + bracket layers in Glyphs source has been rather difficult. Also, hint matching is more complex. Therefore, moving forward, the source will be UFO + designspace. The contours will be converted to quadratic using `cu2qu` to ensure greater fidelity. (Point numbers will undoubtedly change, therefore manual hinting will have to be done again.)

to-do:

- [x] make UFOs
- [x] convert using `cu2qu`
- [x] make quadratic outlines compatible
- [x] make designspace
- [x] build TTFs using `fontmake`
- [x] proof metrics/kerning/outlines using `diffenator`
- [x] manually hint VFs
- [x] proof rendering using `diffenator`/`diffbrowsers`
- [x] instantiate static weights from hinted VFs
- [x] manually tune instances (if necessary)
- [ ] write post-mortem doc on bumps and tips and optimistic timeframe for completing a project like this

**Comment by anthrotype** [comment]
@laerm0 when you convert the outlines with cu2qu, make sure you are reversing the contour direction correctly -- you don't want too realise after you did manual hinting that "ops, I forgot to check outlines are set to to clockwise direction".
So, if the original PostScript outlines in the .glyphs sources are set in counter-clockwise direction (as they should), then let cu2qu flip that as part of the outline conversion.
The cu2qu command line script always reverses the contours directions by default, unless you pass `--keep-direction` option (fontmake itself does the same).
The default behavior if you use the programmatic interface `cu2qu.ufo.fonts_to_quadratic` is to _not_ reverse direction, unless `reverse_direction=True` option is used.
Note that cu2qu does not (cannot) fix the contour direction for you, it simply inverts all the contour directions (what was counter-clockwise becomes clockwise, or viceversa).
Sorry if i'm stating the obvious. Let me know if you have any questions.

**Comment by laerm0** [comment]
@anthrotype Is it possible to use `cu2qu` in Glyphs? If I could convert to quadratic there and then export the UFO that will make a lot more sense.

**Comment by anthrotype** [comment]
nope. What's wrong with exporting to UFOs, running cu2qu outside Glyphs, then re-convert UFOs to glyphs using ufo2glyphs if you wish to check them within Glyphs?

**Comment by laerm0** [comment]
It just seems silly to bring them back into Glyphs. That's all.

**Comment by anthrotype** [comment]
why do you need to bring them back into Glyphs?

**Comment by laerm0** [comment]
To double-check that they're compatible for interpolation.

**Comment by anthrotype** [comment]
there is no need to _check_ because cu2qu will blow up on you if they weren't interpolation-compatible to begin with and it's got its own test suite for that to guarantee the output is correct.

**Comment by laerm0** [comment]
Ah, okay, cool. Thanks!

**Comment by laerm0** [comment]
Closing with checklist complete as the last step is occurring elsewhere (namely in issues filed here and compiled in a Google doc).
